name: Working directories and shells
on: [push]
jobs:
    display-working-directories-ubuntu:
        runs-on: ubuntu-latest
        steps:
            - name: Display working directory & list files
              run: |
                pwd
                ls -a
                echo $GITHUB_SHA
                echo $GITHUB_REPOSITORY
                echo $GITHUB_WORKSPACE

    display-working-directories-windows:
        runs-on: windows-latest
        steps:
            - name: Display working directory & list files
              run: |
                pwd
                ls -a
                echo $GITHUB_SHA
                echo $GITHUB_REPOSITORY
                echo $GITHUB_WORKSPACE